logging:
  level:
    root: INFO
    br.eti.archanjo: INFO
    org.springframework: INFO
    br.eti.archanjo.webcron.quartz: INFO
spring:
  profiles:
    active: default
  application:
    name: backup-service
  redis:
    database: 15
    host: vm.services
    port: 6379
    timeout: 120000
    pool:
      max-active: 16
      max-idle: 4
      max-wait: -1
  datasource:
    url: jdbc:mysql://vm.services:3306/webcrons?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: q1w2e3
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: vm.services
      database: webcron
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080
  tomcat:
    remote-ip-header: X-Forwarded-For

management:
  context-path: /management
  port: 8081

webcron:
  httplimits:
    limit: 100
    page: 0
  logging:
    folder: /Users/fabricio/1/log